// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmQXJei9ZikUAEQ6_yRrN19R4kGh8A-pc',
    appId: '1:880798076515:web:1b4b1e008d1f3e91d37256',
    messagingSenderId: '880798076515',
    projectId: 'itasks-c9fea',
    authDomain: 'itasks-c9fea.firebaseapp.com',
    databaseURL:
        'https://itasks-c9fea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itasks-c9fea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnHJdTV5vPNkz923gyMYeRCBX14Wo7Wyw',
    appId: '1:880798076515:android:e0fe5f8889387381d37256',
    messagingSenderId: '880798076515',
    projectId: 'itasks-c9fea',
    databaseURL:
        'https://itasks-c9fea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itasks-c9fea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1p5wwhsyNF9zybGI6DLo09MNH4je8I2o',
    appId: '1:880798076515:ios:d51b7cf4e0549d00d37256',
    messagingSenderId: '880798076515',
    projectId: 'itasks-c9fea',
    databaseURL:
        'https://itasks-c9fea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itasks-c9fea.firebasestorage.app',
    iosBundleId: 'com.example.itasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1p5wwhsyNF9zybGI6DLo09MNH4je8I2o',
    appId: '1:880798076515:ios:d51b7cf4e0549d00d37256',
    messagingSenderId: '880798076515',
    projectId: 'itasks-c9fea',
    databaseURL:
        'https://itasks-c9fea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itasks-c9fea.firebasestorage.app',
    iosBundleId: 'com.example.itasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmQXJei9ZikUAEQ6_yRrN19R4kGh8A-pc',
    appId: '1:880798076515:web:0575eccc31bf6ae2d37256',
    messagingSenderId: '880798076515',
    projectId: 'itasks-c9fea',
    authDomain: 'itasks-c9fea.firebaseapp.com',
    databaseURL:
        'https://itasks-c9fea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itasks-c9fea.firebasestorage.app',
  );
}
